### ISSUE TITLE
Full k8s deployment

### ISSUE THREAD

**Issue by maceyldn** [Opendigitalradio/ODR-AudioEnc#22]
Would be great if we could orchestrate the components directly into k8s enabling quick service scaling e.t.c.

I think we'd need the following for starters.

1) Work to EncoderManager to make it more a "Mux Manager", enabling complete service control.
2) Each application (AudioEnc/Mux) config changing to a rest api approach.
3) K8s Operators to configure the mux and audio encoders, The encoder would just deploy a crd for new service.

Thoughts?

A

**Comment by mpbraendli** [comment]
I don't believe the ODR tools should be tailored specifically for k8s or any other deployment technique. If something gets in the way you want to deploy the tools, please let me know, maybe we can simplify things.

I'm going to close the issue because it's more a request for a discussion, and for that the mailing list is more appropriate https://groups.io/g/odr-mmbtools
